---
# Source: prometheus-operator/templates/alertmanager/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-monitoring-prometheus-oper-alertmanager
  namespace: monitoring
  labels:
    app: prometheus-operator-alertmanager
    
    chart: prometheus-operator-6.20.3
    release: "monitoring"
    heritage: "Tiller"
data:
  alertmanager.yaml: "Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0KcmVjZWl2ZXJzOgotIG5hbWU6ICJudWxsIgotIGVtYWlsX2NvbmZpZ3M6CiAgLSBhdXRoX2lkZW50aXR5OiBtYXJrdGFsc3RvbkBnbWFpbC5jb20KICAgIGF1dGhfcGFzc3dvcmQ6IHFhY2Vkbm1janZ6anlwZGsKICAgIGF1dGhfdXNlcm5hbWU6IG1hcmt0YWxzdG9uQGdtYWlsLmNvbQogICAgZnJvbTogbWFya3RhbHN0b25AZ21haWwuY29tCiAgICBzbWFydGhvc3Q6IHNtdHAuZ21haWwuY29tOjU4NwogICAgdG86IG1hcmt0YWxzdG9uQGdtYWlsLmNvbQogIG5hbWU6IGVtYWlsCnJvdXRlOgogIGdyb3VwX2J5OgogIC0gYWxlcnRuYW1lCiAgLSBpbnN0YW5jZQogIGdyb3VwX2ludGVydmFsOiA1bQogIGdyb3VwX3dhaXQ6IDMwcwogIHJlY2VpdmVyOiBlbWFpbAogIHJlcGVhdF9pbnRlcnZhbDogMTJoCiAgcm91dGVzOgogIC0gbWF0Y2g6CiAgICAgIGFsZXJ0bmFtZTogV2F0Y2hkb2cKICAgIHJlY2VpdmVyOiAibnVsbCIKICAtIG1hdGNoOgogICAgICBhbGVydG5hbWU6IENQVVRocm90dGxpbmdIaWdoCiAgICByZWNlaXZlcjogZW1haWwK"
