---
# Source: prometheus-operator/templates/alertmanager/servicemonitor.yaml

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-prometheus-oper-alertmanager
  namespace: monitoring
  labels:
    app: prometheus-operator-alertmanager
    
    chart: prometheus-operator-6.20.3
    release: "monitoring"
    heritage: "Tiller"
spec:
  selector:
    matchLabels:
      app: prometheus-operator-alertmanager
      release: "monitoring"
  namespaceSelector:
    matchNames:
      - "monitoring"
  endpoints:
  - port: web
    path: "/metrics"
