{{- if and .Values.pksMonitor.enabled .Values.global.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "pks-monitor.fullname" . }}-pks-monitor
  labels:
    app: {{ template "pks-monitor.name" . }}-pks-monitor
{{ include "pks-monitor.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "pks-monitor.fullname" . }}-pks-monitor
subjects:
- kind: ServiceAccount
  name: {{ template "pks-monitor.pksMonitor.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
