{{- if and .Values.pksMonitor.enabled .Values.pksMonitor.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pks-monitor.pksMonitor.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "pks-monitor.name" . }}-pks-monitor
{{ include "pks-monitor.labels" . | indent 4 }}
imagePullSecrets:
{{ toYaml .Values.global.imagePullSecrets | indent 2 }}
{{- end }}
