prometheus:
  prometheusSpec:
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
    configMaps:
      - bosh-target-groups
    replicas: 1
    externalUrl: ((prometheus_url))
    externalLabels:
      cluster: ((cluster_name))
      foundation: ((foundation))
    secrets:
      - etcd-client
    ruleSelector:
      matchLabels:
        app: prometheus-operator
        release: prometheus-operator
    enableAdminAPI: true
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: thin-disk
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
        selector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - prometheus
    additionalScrapeConfigs:
    - job_name: "kubeEtcd-((cluster_name))"
      file_sd_configs:
      - files:
        - '/etc/prometheus/configmaps/bosh-target-groups/bosh_target_groups.json'
      scheme: https
      tls_config:
        ca_file: "/etc/prometheus/secrets/etcd-client/etcd-client-ca.crt"
        cert_file: "/etc/prometheus/secrets/etcd-client/etcd-client.crt"
        key_file:  "/etc/prometheus/secrets/etcd-client/etcd-client.key"
        server_name: "*.etcd.cfcr.internal"
      relabel_configs:
      - source_labels: [__meta_bosh_job_process_name]
        regex: etcd
        action: keep
      - source_labels: [__meta_bosh_deployment]
        regex: ((service_instance_id))
        action: keep
      - source_labels: [__address__]
        regex:  '(.*)'
        target_label: __address__
        replacement: '${1}:2379'
