apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "prometheus-deployment.prometheusOperator.releaseName" . }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.alertmanager.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "prometheus-deployment.prometheusOperator.releaseName" . }}-alertmanager
          servicePort: 9093
  - host: {{ .Values.grafana.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "prometheus-deployment.prometheusOperator.releaseName" . }}-grafana
          servicePort: 80
  - host: {{ .Values.prometheus.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "prometheus-deployment.prometheusOperator.releaseName" . }}-prometheus
          servicePort: 9090
  tls:
  - hosts:
    - {{ .Values.alertmanager.host }}
    - {{ .Values.grafana.host }}
    - {{ .Values.prometheus.host }}
    # secretName: pks-tls-secret
