---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: malston/pks-control-plane
    tag: latest

inputs:
  - name: prometheus-operator

run:
  path: prometheus-operator/ci/install-operator/task.sh

params:
  FOUNDATION:
  NAMESPACE:
  RELEASE:
  VERSION: