{{- if and .Values.boshExporter.enabled .Values.boshExporter.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "bosh-exporter.boshExporter.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "bosh-exporter.name" . }}-bosh-exporter
{{ include "bosh-exporter.labels" . | indent 4 }}
imagePullSecrets:
{{ toYaml .Values.global.imagePullSecrets | indent 2 }}
{{- end }}
