apiVersion: v1
data:
  prometheus-additional.yaml: LSBqb2JfbmFtZTogInByb21ldGhldXMtY2x1c3RlcjAyIgogIHNjaGVtZTogaHR0cAogIGhvbm9yX2xhYmVsczogdHJ1ZQogIG1ldHJpY3NfcGF0aDogIi9mZWRlcmF0ZSIKICBzY3JhcGVfaW50ZXJ2YWw6IDMwcwogIHBhcmFtczoKICAgICdtYXRjaFtdJzoKICAgICAtICd7X19uYW1lX189fiIuKyJ9JwogIHN0YXRpY19jb25maWdzOgogIC0gdGFyZ2V0czogWyJwcm9tZXRoZXVzLTAyLmhhYXMtNDQwLnBlei5waXZvdGFsLmlvIl0K
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
  namespace: monitoring
