---
# Source: prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name:  monitoring-prometheus-oper-admission-create
  namespace: monitoring
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: prometheus-operator-admission-create    
    chart: prometheus-operator-6.20.3
    release: "monitoring"
    heritage: "Tiller"
spec:
  template:
    metadata:
      name:  monitoring-prometheus-oper-admission-create
      labels:
        app: prometheus-operator-admission-create        
        chart: prometheus-operator-6.20.3
        release: "monitoring"
        heritage: "Tiller"
    spec:
      containers:
        - name: create
          image: jettech/kube-webhook-certgen:v1.0.0
          imagePullPolicy: 
          args:
            - create
            - --host=monitoring-prometheus-oper-operator,monitoring-prometheus-oper-operator.monitoring.svc
            - --namespace=monitoring
            - --secret-name=monitoring-prometheus-oper-admission
      restartPolicy: OnFailure
      serviceAccountName: monitoring-prometheus-oper-admission
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
