---
# Source: prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/role.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name:  monitoring-prometheus-oper-admission
  namespace: monitoring
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: prometheus-operator-admission    
    chart: prometheus-operator-6.20.3
    release: "monitoring"
    heritage: "Tiller"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
