---
# Source: prometheus-operator/templates/prometheus-operator/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: monitoring-prometheus-oper-operator
  namespace: monitoring
  labels:
    app: prometheus-operator-operator
    
    chart: prometheus-operator-6.20.3
    release: "monitoring"
    heritage: "Tiller"
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: prometheus-operator-operator
    release: "monitoring"
  type: "ClusterIP"
