apiVersion: v1
kind: Service
metadata:
  name: monitoring-alertmanager-lb
  labels:
    app: alertmanager
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 9093
  - name: https
    port: 443
    targetPort: 9093
  selector:
    app: alertmanager
