apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-03-ingress
spec:
  tls:
  - hosts:
    - grafana-03.haas-440.pez.pivotal.io
    secretName: grafana-lb-tls
  rules:
  - host: grafana-03.haas-440.pez.pivotal.io
    http:
      paths:
      - path: /
        backend:
          serviceName: monitoring-grafana-lb
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-grafana-lb
  labels:
    app: grafana
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
  - name: https
    port: 443
    targetPort: 3000
  selector:
    app: grafana
