apiVersion: v1
kind: Service
metadata:
  name: monitoring-grafana-lb
  labels:
    app: grafana
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: grafana
