apiVersion: v1
kind: Service
metadata:
  name: monitoring-prometheus-lb
  labels:
    app: prometheus
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 9090
  - name: https
    port: 443
    targetPort: 9090
  selector:
    app: prometheus
