# Default values for ingress-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Provide a name in place of ingress-gateway for `app:` labels
##
nameOverride: ""

## Provide a name to substitute for the full names of resources
##
fullnameOverride: ""

alertmanager:
  host: ""

grafana:
  host: ""

prometheus:
  host: ""

istio:
  enabled: false
  hosts: 
    - '*.cluster01.haas-420.pez.pivotal.io'

ingress:
  enabled: false
