---
# Source: prometheus-operator/templates/prometheus/clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-prometheus-oper-prometheus
  namespace: monitoring
  labels:
    app: prometheus-operator-prometheus
    
    chart: prometheus-operator-6.20.3
    release: "monitoring"
    heritage: "Tiller"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-prometheus-oper-prometheus
subjects:
  - kind: ServiceAccount
    name: monitoring-prometheus-oper-prometheus
    namespace: monitoring

