---
# Source: prometheus-operator/templates/prometheus/prometheus.yaml

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: monitoring-prometheus-oper-prometheus
  namespace: monitoring
  labels:
    app: prometheus-operator-prometheus
    
    chart: prometheus-operator-6.20.3
    release: "monitoring"
    heritage: "Tiller"
spec:
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: monitoring-prometheus-oper-alertmanager
        port: web
        pathPrefix: "/"
  baseImage: quay.io/prometheus/prometheus
  version: v2.12.0
  externalUrl: http://monitoring-prometheus-oper-prometheus.monitoring:9090
  paused: false
  replicas: 1
  logLevel:  info
  logFormat:  logfmt
  listenLocal: false
  enableAdminAPI: true
  retention: "10d"
  routePrefix: "/"
  secrets:
    - etcd-client
    
  serviceAccountName: monitoring-prometheus-oper-prometheus
  serviceMonitorSelector:
    matchLabels:
      release: "monitoring"

  serviceMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: "monitoring"

  podMonitorNamespaceSelector: {}
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      app: prometheus-operator
      release: monitoring
      role: alert-rules
    
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: kubernetes.io/hostname
        labelSelector:
          matchLabels:
            app: prometheus
            prometheus: monitoring-prometheus-oper-prometheus
  additionalScrapeConfigs:
    name: monitoring-prometheus-oper-prometheus-scrape-confg
    key: additional-scrape-configs.yaml
  containers:
    - env:
      - name: BOSH_EXPORTER_BOSH_LOG_LEVEL
        value: debug
      - name: BOSH_EXPORTER_BOSH_URL
        value: 172.16.1.11
      - name: BOSH_EXPORTER_BOSH_UAA_CLIENT_ID
        value: ops_manager
      - name: BOSH_EXPORTER_BOSH_UAA_CLIENT_SECRET
        value: EdyCNlv4r3bArQY1__HgucBwQj6VGStq
      - name: BOSH_EXPORTER_BOSH_CA_CERT_FILE
        value: /etc/bosh-exporter/certs/bosh-ca.crt
      - name: BOSH_EXPORTER_METRICS_ENVIRONMENT
        value: pks
      - name: BOSH_EXPORTER_FILTER_COLLECTORS
        value: ServiceDiscovery
      - name: BOSH_EXPORTER_SD_FILENAME
        value: /var/vcap/store/bosh-exporter/bosh_target_groups.json
      image: harbor.haas-440.pez.pivotal.io/prometheus/boshprometheus/bosh-exporter:3.3.0
      imagePullPolicy: IfNotPresent
      name: bosh-exporter
      ports:
      - containerPort: 9190
        name: http
        protocol: TCP
      volumeMounts:
      - mountPath: /etc/bosh-exporter/certs
        name: certs
        readOnly: true
      - mountPath: /var/vcap/store/bosh-exporter
        name: bosh-target-groups
    
  volumes:
    - name: certs
      secret:
        secretName: bosh-ca
    - hostPath:
        path: /var/vcap/store/bosh-exporter
        type: DirectoryOrCreate
      name: bosh-target-groups
    
