---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: malston/pks-control-plane
  # source:
  #   repository: harbor.haas-420.pez.pivotal.io/library/malston/pks-control-plane
  #   insecure_registries: [harbor.haas-420.pez.pivotal.io]
  #   tag: 0.0.1

inputs:
  - name: repo
  - name: version

outputs:
  - name: charts-commit

run:
  path: repo/ci/tasks/helm-fetch/task.sh

params:
  RELEASE:
  VERSION:
  CHART_REPO: