---
# Source: prometheus-operator/templates/grafana/configmaps-datasources.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-prometheus-oper-grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
    app: prometheus-operator-grafana
    
    chart: prometheus-operator-6.20.3
    release: "monitoring"
    heritage: "Tiller"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://monitoring-prometheus-oper-prometheus:9090/
      access: proxy
      isDefault: true
