resources:
- name: prometheus-deployment
  type: git
  source:
    uri: ((config.uri))
    branch: ((config.branch))

jobs:
- name: install-prometheus-operator
  plan:
  - get: prometheus-deployment
    trigger: true

  - task: pks-login
    file: prometheus-deployment/ci/tasks/pks-login/task.yml
    params:
      PKS_API_URL: ((pks_api_url))
      PKS_USER: ((pks_user))
      PKS_PASSWORD: ((pks_password))
      K8S_CLUSTER_NAME: ((k8s_cluster_name))

  - task: install-operator
    file: prometheus-deployment/ci/tasks/install-operator/task.yml
    params:
      OPSMAN_HOSTNAME: ((opsman_hostname))
      OPSMAN_USER: ((opsman_user))
      OPSMAN_PASSWORD: ((opsman_password))
      OPSMAN_SKIP_SSL_VALIDATION: ((opsman_skip_ssl_validation))
      BOSH_UAA_CLIENT_ID: ((bosh_uaa_client_id))
      BOSH_UAA_CLIENT_SECRET: ((bosh_uaa_client_secret))
      FOUNDATION: ((foundation))
      NAMESPACE: ((namespace))
      RELEASE: ((release))
      VERSION: ((version))
