---
# Source: prometheus-operator/templates/exporters/kube-etcd/servicemonitor.yaml

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-prometheus-oper-kube-etcd
  namespace: monitoring
  labels:
    app: prometheus-operator-kube-etcd
    
    chart: prometheus-operator-6.20.3
    release: "monitoring"
    heritage: "Tiller"
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: prometheus-operator-kube-etcd
      release: "monitoring"
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http-metrics
    interval: 30s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    scheme: https
    tlsConfig:
      serverName: '*.etcd.cfcr.internal'
      caFile: /etc/prometheus/secrets/etcd-client/etcd-client-ca.crt
      certFile: /etc/prometheus/secrets/etcd-client/etcd-client.crt
      keyFile: /etc/prometheus/secrets/etcd-client/etcd-client.key
      insecureSkipVerify: false
