apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bosh-exporter
  labels:
    app: bosh-exporter
    release: {{ .Values.prometheus.release }}
spec:
  selector:
    matchLabels:
      app: bosh-exporter
      release: {{ .Values.prometheus.release }}
  endpoints:
  - port: http-metrics
    interval: 1m
    scrapeTimeout: 30s
