{{- if (not .Values.ingress.enabled) -}}
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator-grafana-lb
  labels:
    app: grafana
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
  - name: https
    port: 443
    targetPort: 3000
  selector:
    app: grafana
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator-alertmanager-lb
  labels:
    app: alertmanager
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 9093
  - name: https
    port: 443
    targetPort: 9093
  selector:
    app: alertmanager
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator-prometheus-lb
  labels:
    app: prometheus
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 9090
  - name: https
    port: 443
    targetPort: 9090
  selector:
    app: prometheus
{{- end }}