---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor.haas-440.pez.pivotal.io/library/malston/pks-control-plane
    insecure_registries: [harbor.haas-440.pez.pivotal.io]
    tag: 0.0.1

inputs:
  - name: prometheus-deployment

outputs:
- name: pks-config
- name: kube-config

params:
  PKS_API_URL:
  PKS_USER:
  PKS_PASSWORD:
  K8S_CLUSTER_NAME:

run:
  path: prometheus-deployment/ci/pks-login/task.sh
