{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: monitoring-istio-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.{{ .Values.clusterDomain }}"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: monitoring-grafana
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "grafana.{{ .Values.clusterDomain }}"
  gateways:
  - monitoring-istio-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: prometheus-operator-grafana
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: monitoring-prometheus
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "prometheus.{{ .Values.clusterDomain }}"
  gateways:
  - monitoring-istio-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: prometheus-operator-prometheus
        port:
          number: 9090
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: monitoring-alertmanager
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "alertmanager.{{ .Values.clusterDomain }}"
  gateways:
  - monitoring-istio-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: prometheus-operator-alertmanager
        port:
          number: 9093
{{- end }}